backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
public_folder: content
publish_mode: editorial_workflow
collections:
  - name: pages
    label: Pages
    folder: content
    slug: "{{slug}}"
    create: true
    extension: mdx
    format: frontmatter
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - { name: body, label: Body, widget: markdown }
